repos:
  - repo: local
    hooks:
      - id: black
        name: black (system)
        entry: black
        language: system
        types: [python]

      - id: mypy
        name: mypy (system)
        entry: mypy
        language: system
        types: [python]
        args: [--explicit-package-bases]

      - id: flake8
        name: flake8 (system)
        entry: flake8
        language: system
        types: [python]
